use-cache: true
clear-cache-on-death: false

teams:
    admins:
        permission: "magicjutsus.team.admins"
        friendly-fire: false
    team1:
        permission: "magicjutsus.team.one"
        friendly-fire: false
        can-target:
          - team2
    team2:
        permission: "magicjutsus.team.two"
        friendly-fire: false
        cant-target:
          - admins