name: MagicJutsusTeams
version: $version
main: com.nisovin.magicjutsus.teams.MagicJutsusTeams
authors: [nisovin, TheComputerGeek2]
depend: [MagicJutsus]
commands:
    magicjutsusteams:
        usage: |
            /<command> <create|new|make> <teamname> - makes a new team
            /<command> list - lists the existing teams
            /<command> <info|about> <name> - shows setup information about a team
        permission: magicjutsusteams.manage
        description: Base command for team management.
permissions:
    magicjutsusteams.manage:
        default: op
        description: Manage teams from in game.
