ignore-other-plugins: false
require-known-jutsu: true
require-teach-perm: true

currencies:
    money: "vault"
    levels: "levels"
    xp: "experience"
    gold: "266"
    cocoa: "351:3"

first-line: [JUTSU SHOP]
str-already-known: You already know that jutsu.
str-cant-afford: You cannot afford that jutsu.
str-cant-learn: You are not able to buy that jutsu.
str-purchased: You have purchased the %s jutsu.

first-line-scroll: [SCROLL SHOP]
scroll-jutsu-name: scroll
scroll-item-type: 339
str-cant-afford-scroll: You cannot afford that scroll.
str-purchased-scroll: You have purchased a scroll for the %s jutsu (with %u uses).
str-scroll-fail: You cannot purchase a scroll at this time.