name: MagicJutsusShop
version: $version
main: com.nisovin.magicjutsus.shop.MagicJutsusShop
author: nisovin
depend: [MagicJutsus]
softdepend: [Vault]
permissions:
    magicjutsus.createsignshop:
        description: Create a jutsu shop
        default: op
