name: MagicJutsusMemory
version: $version
main: com.nisovin.magicjutsus.memory.MagicJutsusMemory
depend: [MagicJutsus]
commands:
    magicjutsusmemory:
        description: Check your memory usage
        usage: /<command>
        aliases: [memory,mem]
permissions:
    magicjutsus.memory.checkothers:
        description: Check someone else's memory usage
        default: op
