name: MagicJutsus
main: com.nisovin.magicjutsus.MagicJutsus
version: $version
authors: [nisovin, TheComputerGeek2, Chronoken]
softdepend: [GriefPrevention,Vault,ProtocolLib,WorldGuard,Residence,PowerNBT,LibsDisguises,NoCheatPlus,PlaceholderAPI]
api-version: "1.13"

#depend: [EffectLib]
commands:
    magicjutsucast:
        description: Cast a jutsu
        usage: /<command>
        aliases: [cast,c]
    magicjutsumana:
        description: Show mana bar
        usage: /<command>
        aliases: [mana]
    magicjutsuxp:
        description: Show magic XP info
        usage: /<command>
        aliases: [magicxp,jutsuxp]
